version: "3.9"
services:
  emtsv:
    image: "mtaril/emtsv"
    ports:
      - "5000:5000"
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - "emtsv"
    links:
      - "emtsv:mtaril/emtsv"
